services:
  db:
    container_name: SportsPeak
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - /var/lib/postgresql/data
