spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: SportsPeak
# DB CONNECTION
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changemeinprod!
    driver-class-name: org.postgresql.Driver
# JPA
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        type:
          preferred_duration_jdbc_type: INTERVAL_SECOND
# DGS Framework
dgs:
  graphql:
    path: /service/api/graphql
    schema-locations: classpath*:/graphql/**/*.graphql*
# SECURITY
security:
  jwt:
    token:
      secret-key: Y2hhbmdlbWVpbnByb2QhY2hhbmdlbWVpbnByb2Qh