spring:
  # FILE UPLOAD
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  # COLOR IN CONSOLE :D
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: SportsPeak

  # DB CONNECTION
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changemeinprod!
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        enable_lazy_load_no_trans: true
        type:
          preferred_duration_jdbc_type: INTERVAL_SECOND
        show_sql: false

# DGS Framework
dgs:
  graphql:
    path: /service/api/graphql
    schema-locations: classpath*:/graphql/**/*.graphql*

# SECURITY
security:
  cors:
    allowed-origin: http://localhost:4200
  jwt:
    token:
      secret-key: Y2hhbmdlbWVpbnByb2QhY2hhbmdlbWVpbnByb2Qh

# TSL / SSL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: SportsPeak
    key-store: classpath:keystore/SportsPeak.p12
    key-store-password: changemeinprod!

# STORAGE
storage:
  location: src/main/resources/static/uploads
